declare let io: any;
declare let socket: any;
declare let localStream: MediaStream;
declare let connection: RTCPeerConnection;
declare let isInitiator: boolean;
declare let remoteIceCandidates: any[];
declare let inCall: boolean;
declare function getUUID(): string;
declare const me: string;
declare const iceServers: RTCIceServer[];
declare const turnServerOne: RTCIceServer;
declare const turnServerTwo: RTCIceServer;
declare const turnServerThree: RTCIceServer;
declare function init(): Promise<void>;
declare function makeCall(event: any): Promise<void>;
declare function setInitiatorLocalSdp(sdp: any): Promise<void>;
declare function sendInitiatorSdp(sdp: RTCSessionDescription): Promise<void>;
declare function createAnswerForOfferReceived(remoteSdp: any): Promise<void>;
declare function setNonInitiatorLocalSdp(sdp: any): Promise<void>;
declare function sendNonInitiatorSdp(sdp: any): Promise<void>;
declare function handleRemoteDescriptionSet(): void;
declare function endCall(event: any): void;
declare function handleAnswerReceived(sdp: any): Promise<void>;
